### ISSUE TITLE
Memory-optimization

### ISSUE THREAD

**Issue by akshaylive** [MrChrisJohnson/logistic-mf#1]
Hi Chris,

I was wondering if there could be a csr_matrix impl of observation_matrix as my matrix is way to big but sparse. I tried changing the source code but the following operations in method "deriv" is consuming a lot of memory.

```
    A = np.dot(self.user_vectors, self.item_vectors.T)
    A += self.user_biases
    A += self.item_biases.T
    A = np.exp(A)
    A /= (A + self.ones)
    A = (self.counts + self.ones) * A
```

Can you think of any alternate way of doing this?

Regards,
Akshay

**Comment by MrChrisJohnson** [comment]
The problem is that the naive implementation here places a weight on every observation (even the 0s), so even if the observation matrix is sparse, the loss function has an entry for all elements (zero and non-zero). 

I think the way around this would be to sample the negatives (zeros) randomly, and decrease \alpha in response. Does that make sense? Then, instead of placing a single negative entry on every 0, we'd have negative entry on some random subset of the 0s, but then decrease the amount of weight on the positives (via \alpha).

**Comment by akshaylive** [comment]
Thanks for such a quick response, Chris. Appreciate it! I read about that idea in your paper. If I may ask, from your practical experience, what % of negative observations do you sample before you see any considerable loss in accuracy? Also, feel free to close this issue, as its resolved. 

P.S. this algorithm performs extremely well and with very low MPR on my sample data set. Can't wait to see how it performs on 25 million users! Thanks for the very well written and useful paper!

**Comment by MrChrisJohnson** [comment]
The sampling is merely a tradeoff between performance and quality so larger sampling should never hurt quality (but may hurt performance). Something between 1k-100k is probably sane. Glad to hear it's working well for you!
